title: 현우의 공유메모장
description: 검색하긴 귀찮고 외우기엔 애매한 것들 모음집
show_downloads: true

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://optboy.github.io" # change this to the base hostname & protocol for your site


google_analytics: UA-160037171-1

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

# theme: # leave it empty
theme:

# social
author: hyunwoo
image: /thumbnail-jumbo.png
twitter:
  username: 

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

markdown: kramdown
  
header_page_refs: ['category', 'about']

disqus_url: 'https-optboy-github-io.disqus.com'
disqus_id: 'https-optboy-github-io'
